#pragma once

#define TILE_SIZE 32
#define VECTOR 16
#define VECTOR_AMOUNT 2

#define STR_(S) #S
#define STR(S) STR_(S)

#define SET_TILE_SIZE "-D TILE=" STR(TILE_SIZE)
#define SET_VECTOR " -D VECTOR=" STR(VECTOR)
#define SET_VECTOR_AMOUNT " -D VECTOR_AMOUNT=" STR(VECTOR_AMOUNT)

#define BUILD_OPTIONS SET_TILE_SIZE SET_VECTOR SET_VECTOR_AMOUNT
